export const ANGELICA_ALBINSON = "ANGELICA ALBINSON";
export const BERWICK_SISTERS = "BERWICK SISTERS";
export const CLAUDETTE_CAZELAR = "CLAUDETTE CAZELAR";
export const GREG_GAFFNEY = "GREG GAFFNEY";
export const MORTIMER_W_MOLLOW = "MORTIMER W MOLLOW";
export const STANLEY_SMITHE = "STANLEY SMITHE";
